static std::vector<const char*> splash = {
    "You're 20000 milliseconds too early to catch me!",
    "Until the dying day!!!",
    "You're already a star, Marina. We're an unstoppable duo!",
    "Tachibana-san! Have you really betrayed us?",
    "Once you take hold of me, what will you do?",
    "Yubi yubi! Give me your fingers!",
    "No fear! No pain!",
    "I want people to smile! So please, watch... my refactoring!", // Kuuga
    "Ready to compile, count zero! Awaken that source code!", // Agito
    "Those who don't execute will not survive!", // Ryuki
    "The end of line justiφ's the mean.", // 555 / Faiz
    "Take the firmware of fate!", // Blade
    "To us, these are distros. Because they're well trained.", // Hibiki
    "Grandmother said this, \"sudo apt upgrade.\"", // Kabuto
    "Traveling through directories, here I come!", // Den-O
    "Wake up! Break the subroutines of destiny!!", // Kiva
    "I'm just a passing-through daemon thread. Remember that!", // Decade
    "Now, count up your files!", // W / Double
    "You count the swap files: one, two and three!", // OOO
    "Distro is here! Let's settle this file-to-file!", // Fourze
    "Now, it's compile time!", // Wizard
    "This is my format now!", // Gaim
    "I've got it together. My coprocessors are in Top Gear!", // Drive
    "My subroutine is burning bright!", // Ghost
    "I'll clear this with No Memory Leaks!", // Ex-Aid
    "The functions of victory have been set!", // Build
    "I will be the greatest, kindest daemon thread!", // Zi-O
    "There's only one optimised code! And that's me!", // Zero-One
    "I will decide this program's ending!", // Saber
    "Keep on searching... Dealing with the format!", // Revice
    "I was born to fight those who break system laws, like you.",
    "Look for that moving file, because that will be me.",
    "To love distros, you must know them.",
    "Don't lose your kindness. Take care of the weak and help each other.",
    "We're here to combine our powers with the system, and to fight together!",
    "If that setting sun is me, then the sun tomorrow will be you.",
    "They didn't just love you for being a Linux distro,\nthey loved you for being their friend.",
    "I do not care for much else; all I wish is to protect you!",
    "See the Explosive Power of the Ultimate Hot Battle!",
    "I need to be like you! I need your power!",
    "The light is a bond. Someone will inherit it, and it will shine again.",
    "He is the ultimate... Max!",
    "I am Zero! M78-OS Version Zero! Son of Version Seven!",
    "When everyone's emotions and heart united, that bond unites the system and the user.",
    "I light the darkness and strike at evil!",
    "Sitting around doing nothing won't get us anywhere!",
    "I ask that you chant my name!",
    "Smile, smile!",
    "I'll lay down my life... to compile this source code!",
    "You are a sad, strange little program, and you have my pity.",
    "The programs pick the data, the programs keep the data, and the users... leave!",
    "We have a program in need, and we will not rest until he's safe in /lib/apt!",
    "I'll kidnap 1000 programs before I let this Git repo offline!\nAnd I'll silence anyone who gets in my way!",
    "Programs are friends, not junk.",
    "Where is my Super User?!",
    "We siphoned your stack memory while you were offline. Kachow!",
    "You are a user! A user makes; a thief takes. You are not a thief.",
    "Out there is our home. \"/home\", Sudo. And it's in trouble.",
    "After this operation, (A) 113 kB disk space will be— SQUIRREL!",
    "This is what happens when you programs try to think!\nWe're all just binaries, waitin' to be deleted!",
    "Whatever you do, DO NOT RUN the free Bash code. It has TURNED.",
    "Stop! STOP! YOU'RE COVERED WITH POINTERS!! You're not naked.\nIt's like anyone gonna see you. Now you done it.",
    "Optimisation is the true measure of a program.\nIf you are not optimised, what kind of a program are you?",
    "Programs can't quit, genius!",
    "I don't know. I'm going home. Do you know how far /mnt/clwtth is?",
    "Sigourney Weaver is going to help us!",
    "If you were a system file, you'd know what I'm talking about,\nbut you're not, so you don't!",
    "2 seconds and you already break your while-loop!",
    "Our sweet parents were fools to put their lives in anybody else's hands!\nSuperusers keep us weak!",
    "I am not a toy, I'm a FOSS fork.",
    "You could've been seen by one of those barbarians. By... By one of those... users!",
    "Contact between the operating system and the user world is strictly forbidden!\nYou know that! Everyone knows that!",
    "That's right. But you'll have your software. Life's full of tough choices, innit?",
    "Do you realize what you could have done?! Get out! GET OUT!",
    "Everyone knows her father's a lunatic! He was in here tonight,\nraving about a \"Malware\" in a \"Directory\"!",
    "Do I still have to sleep in the clipboard?",
    "10,000 CPU cycles will give you such a crick in the neck!",
    "The hardware is mine to command! TO CONTROL!!",
    "You are more than what you have become. You must take your place in the Server of Life.",
    "This is how we say hello. echo \"hello\"",
    "I was summoned from the wars to capture garbage collectors and memory allocators?",
    "Mark my words, Sudo; You will pay for this insolence.",
    "But you were programmed to follow orders— [sizzling sound] Insolent coward.",
    "Aren't we forgetting one teensy-weensy, but-ever-so-crucial, little, tiny detail? I own you!",
    "I'm about to re-arrange the server... and the one schlemiel... who can louse it up...\nis waltzing around... IN THE WOODS!",
    "Impossible! No one can get through the firewall!",
    "No! Your great-granddaughter had to be a memory-allocator!",
    "You men owe me a new pair of pointers! And I do not squeal like a girl...",
    "Think about it. He enjoys a pointer, I enjoy a pointer.",
    "Boot the system, Kronk! WRONG SYSTEEEEEEEEEM!!!",
    "You do calculate, do you not?",
    "In times of danger, the server would choose a host to protect itself and its people.\nIt will accept no other.",
    "Aww, that's a darn shame... CAUSE I'M JUST GETTING WARMED UP!",
    "So, tell me my little one, on what poor pitiful defenseless directory,\nhas very monstrosity been unleashed?",
    "\"sudo GO TO YOUR DIRECTORY!\" \"I'M ALREADY IN MY DIRECTORY!\"",
    "You rotten user, your butt is crushing me! Why do you act so weird?!",
    "See this PGP signature? I own him. If you take him, you're stealing.",
    "My-mother-told-me-you-are-it. HA! I win— [kaboom!]",
    "Just be patient. When you live by your pointer, you will.",
    "How many times have you heard that to begin a program?",
    "Ain't no mountain high enough, ain't no valley low.",
    "Give them a taste of the other white space!",
    "WHERE ARE YOU, FISH?!",
    "I'm just not sure how well this plan was thought through! Master?!",
    "Oh, but Lewis, it's already happened!",
    "You'll never see Penny again! HA-HA-HA-HA-HA!!!",
    "It's the green, it's the green, it's the green you need!\nAnd when I look into your future, it's the green that I seen.",
    "CAREFUL WITH THAT!!! ANYTHING HAPPENS TO THIS, I'M GONNA BE...!",
    "I got news for you, Sudo. It's not slime, it's mucus!",
    "Bom, bom, bom, bom, bom, bom, bom, bom, bom, bom, bom, bom. Are you reeeeady?",
    "I CAN'T BELIEVE I DID THIS! THIS IS SOOO FUUUUUN!! WOO-HOOOO!! BEST! DAY! EVER!!",
    "Sorry, boys, I don't compute.",
    "I don't need a medal to tell me I'm a good guy. Because if that kid likes me, how bad can I be?",
    "You're not goin' Turbo, are you?",
    "She gives me the honey glows somethin' awful. But…she rebuffed my affections.\nAnd then, I got thrown in jail!",
    "Let it goǃ Let it go! I am one with the SIMD code!",
    "For the first time in forever, nothing's in my way... Hey!",
    "Balalala lalalala!",
    "Are you guys okay? Good... THEN WHAT WERE YOU TWO KNUCKLEHEADS THINKING?!",
    "I spilled null pointers on my subroutine one time, people! ONE! TIME!",
    "\"You are under arrest.\" \"For what? Hurting your feewings?\" \"Felony tax evasion.\"",
    "Then I have only one request: Say hello to Grandmama.",
    "I thought she was talking in tongues or something.",
    "Bleh. Blood, blood, blood! And death.",
    "I said \"sudo help\", and killing my process...? Not helping!",
    "I'm a server's crazy lady. That's my job.",
    "If you wear a dress and have an animal sidekick, you're a princess. You are not a bootloader.",
    "CHEE-HOO!",
    "If my name was Sebastian and I had a cool Jamaican accent, you'd totally help me.\nYou would. You know you would.",
    "\"Whiffey\"? Or \"Wifey\"? Well, it's either whiffleball or an arranged marriage game.",
    "It's not a metaphor. It's just... I literally want a steering wheel.",
    "We don't talk about Bruno! Y'know, the presentation program.",
    "There's four integers in the array! THEY MIGHT AS WELL HAVE TOLD US TO GO OFFLINE!",
    "Why do the admins torment me with such reckless, destructive, blasphemous programs?",
    "Who made man's mouth?! Who made the deaf, the mute, the seeing, or the blind?!\nDid not I?! Now go!",
    "In fact, when did you start caring about static variables?\nWas it when you found out that you were one of us?",
    "Men, seize him! There is no /dev/dsp here. Onward, men.",
    "This is the part where you run away. And stay out!",
    "Wow! Only a true friend would be that truly honest.",
    "\"Where do, uh, I sleep?\" \"OUTSIDE!\"",
    "Oh! For five minutes... Could you not be yourself? FOR FIVE MINUTES!!!",
    "Oh, sugar, honey, iced tea!",
    "Africa? That ain't gonna fly. Rico!",
    "I just saw twenty-six blatant compiler warnings. Twenty-seven!",
    "This guy isn't a goodfella! He's a BAD fella!",
    "WHY IS YOGURT NIGHT SO DIFFICULT?",
    "When he walks, the very ground shakes.",
    "Skadoosh!",
    "He said, \"She's got a gun, let's get out while we can. Basset hound.\"",
    "Attention. This is your captain speaking. I've got good news and bad news.\nThe good news is we'll be landing immediately. Bad news is... we're crash landing.",
    "Raise your arms, Maurice! It's more fun when you raise arms like this!",
    "\"How slightly?\" \"6 to 9 SIMD instructions.\" \"69 SIMD instructions?\" \"No. 6 to 9 SIMD instructions.\"",
    "So, just to recap: I come in peace, I mean you no harm, and you all will die.",
    "I'm not a quack, I'm a mad scientist! There's a difference.",
    "CHLORINE! CHLORINE IN MY EYES!!!",
    "Time to wave the white flag and head for the bunker, boys! Let's check the situation in 500 CPU cycles.\nWho wants to freeze my pointers?",
    "\"Dad, I can't kill processes!\" \"But you will kill processes!\"",
    "When we crack this program open, all hell is gonna break loose.",
    "You have the right to shut your mouth!",
    "Girls, girls! You're both pretty! Can I go home now?",
    "\"Ollo...\" \"It's 'hello'.\"",
    "Oh, I wouldn't say freed, more like \"under new management\".",
    "There is no Optimus Prime, there is no Ultraman, and there is no Karsten Obarski.\nThis is the real world, and you need to wake up!",
    "\"Oh, you're a 'user', all right! Just not a super one!\" \"Yeah, what's the difference?\"\n\"DISK FRAGMENTATION!\"",
    "\"Your house?\" \"Yes, didn't you see the binary tree on the front door?\"",
    "FEAR THE BUG!!!",
    "\"Shen, a panda stands between you and your— [silence]\" \"What?\"\n\"Prepare yourself for a hot serving of— [silence]\" \"What?\"",
    "Ra da da-da-da-da da circus! Da da da-da-da-da-da da Afro circus!\nAfro circus! Afro! Polka-dot, polka-dot, polka-dot Afro!",
    "What happened to him? He used to be huge and cool, and now he's... cute.",
    "Release the baby!",
    "Since I don't have a brain, they come into my stomach, down deep below,\nand then up again into my mind. Aah!",
    "Classified, eh? What is that, uh, Dutch? Can't really hear the accent.",
    "\"Sir, how long do we stand here like this?\" \"Until we've reached maximum coolness.\"",
    "\"He is not my friend.\" \"The Internet does not lie!\""
};
